import type { Metadata } from "next";
import { Questrial } from "next/font/google";
import "../globals.css";
import { NextIntlClientProvider } from "next-intl";
import { routing } from "../../i18n/routing";
import { notFound } from "next/navigation";
import { getMessages } from "next-intl/server";

const inter = Questrial({ subsets: ["latin"], weight: ["400"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  if (!routing.locales.includes(params.locale as any)) {
    notFound();
  }

  const messages = await getMessages();
  const env = process.env.NODE_ENV;

  return (
    <>
      <head>
        {/* Self hosted Analytics */}
        {env === "production" && (
          <script
            defer
            src="https://umami.max07.ch/script.js"
            data-website-id="246a00fd-70ff-4a21-be73-bcfd5d1a120c"
          />
        )}
      </head>
      <html lang={params.locale}>
        <body className={inter.className}>
          <NextIntlClientProvider messages={messages}>
            {children}
          </NextIntlClientProvider>
        </body>
      </html>
    </>
  );
}
